
INSERT INTO public.fragrance_notes (name, category, family, intensity, longevity, personality_matches, occasions, climates, age_ranges, description) VALUES
-- TOP NOTES - Fresh
('Bergamot', 'top', 'fresh', 7, 3, '["adventurous","creative","sophisticated"]', '["daily","work","date"]', '["warm","tropical","temperate"]', '["18-24","25-34","35-44"]', 'Bright citrus with subtle floral undertone'),
('Lemon', 'top', 'citrus', 8, 2, '["energetic","adventurous","playful"]', '["daily","sport","outdoor"]', '["warm","tropical","hot"]', '["18-24","25-34"]', 'Sharp, clean citrus burst'),
('Grapefruit', 'top', 'citrus', 7, 2, '["energetic","playful","creative"]', '["daily","sport","casual"]', '["warm","tropical","temperate"]', '["18-24","25-34"]', 'Tangy, slightly bitter citrus'),
('Orange', 'top', 'citrus', 6, 3, '["playful","romantic","creative"]', '["daily","casual","date"]', '["warm","temperate"]', '["18-24","25-34","35-44"]', 'Sweet and juicy citrus'),
('Mandarin', 'top', 'citrus', 5, 3, '["romantic","sophisticated","gentle"]', '["date","evening","casual"]', '["warm","temperate"]', '["25-34","35-44","45+"]', 'Delicate sweet citrus'),
('Lime', 'top', 'citrus', 7, 2, '["energetic","adventurous","playful"]', '["sport","outdoor","daily"]', '["tropical","warm","hot"]', '["18-24","25-34"]', 'Zesty green citrus'),
('Yuzu', 'top', 'citrus', 6, 3, '["creative","sophisticated","adventurous"]', '["daily","work","casual"]', '["temperate","cool"]', '["25-34","35-44"]', 'Japanese citrus with floral nuance'),
('Mint', 'top', 'fresh', 8, 2, '["energetic","adventurous","bold"]', '["sport","daily","outdoor"]', '["warm","hot","tropical"]', '["18-24","25-34"]', 'Cool, invigorating freshness'),
('Green Tea', 'top', 'fresh', 4, 3, '["calm","sophisticated","gentle"]', '["daily","work","meditation"]', '["temperate","cool"]', '["25-34","35-44","45+"]', 'Light, calming green freshness'),
('Sea Salt', 'top', 'fresh', 5, 4, '["adventurous","calm","creative"]', '["outdoor","casual","daily"]', '["coastal","tropical","temperate"]', '["18-24","25-34","35-44"]', 'Oceanic mineral freshness'),
('Cucumber', 'top', 'fresh', 3, 2, '["calm","gentle","sophisticated"]', '["daily","work","spa"]', '["warm","temperate"]', '["25-34","35-44","45+"]', 'Cool, clean, watery green'),
-- HEART NOTES - Floral
('Rose', 'heart', 'floral', 6, 6, '["romantic","sophisticated","gentle"]', '["date","evening","wedding"]', '["temperate","cool"]', '["25-34","35-44","45+"]', 'Classic romantic floral'),
('Jasmine', 'heart', 'floral', 7, 6, '["romantic","sophisticated","sensual"]', '["date","evening","special"]', '["warm","tropical","temperate"]', '["25-34","35-44"]', 'Rich, intoxicating white floral'),
('Lavender', 'heart', 'floral', 5, 5, '["calm","gentle","sophisticated"]', '["daily","spa","meditation"]', '["temperate","cool","warm"]', '["25-34","35-44","45+"]', 'Soothing herbal floral'),
('Iris', 'heart', 'floral', 6, 7, '["sophisticated","elegant","creative"]', '["work","evening","special"]', '["temperate","cool"]', '["35-44","45+"]', 'Powdery, elegant floral'),
('Ylang-Ylang', 'heart', 'floral', 8, 6, '["sensual","romantic","bold"]', '["date","evening","special"]', '["tropical","warm"]', '["25-34","35-44"]', 'Exotic, heady tropical floral'),
('Gardenia', 'heart', 'floral', 7, 5, '["romantic","elegant","gentle"]', '["date","wedding","evening"]', '["warm","tropical"]', '["25-34","35-44","45+"]', 'Creamy, lush white floral'),
('Lily', 'heart', 'floral', 5, 5, '["gentle","elegant","romantic"]', '["daily","wedding","work"]', '["temperate","cool"]', '["25-34","35-44"]', 'Clean, fresh floral'),
('Magnolia', 'heart', 'floral', 6, 5, '["elegant","sophisticated","gentle"]', '["daily","work","date"]', '["warm","temperate"]', '["25-34","35-44","45+"]', 'Citrusy, creamy floral'),
-- HEART NOTES - Fruity
('Apple', 'heart', 'fruity', 5, 4, '["playful","energetic","creative"]', '["daily","casual","sport"]', '["temperate","cool"]', '["18-24","25-34"]', 'Crisp, sweet green fruit'),
('Peach', 'heart', 'fruity', 5, 4, '["romantic","playful","gentle"]', '["daily","casual","date"]', '["warm","temperate"]', '["18-24","25-34"]', 'Soft, velvety stone fruit'),
('Pear', 'heart', 'fruity', 4, 4, '["gentle","elegant","creative"]', '["daily","work","casual"]', '["temperate","cool"]', '["25-34","35-44"]', 'Delicate, juicy fruit'),
('Blackcurrant', 'heart', 'fruity', 6, 5, '["bold","creative","adventurous"]', '["evening","casual","date"]', '["temperate","cool"]', '["18-24","25-34"]', 'Tart, dark berry'),
('Fig', 'heart', 'fruity', 5, 5, '["sophisticated","creative","calm"]', '["evening","date","casual"]', '["warm","temperate"]', '["25-34","35-44"]', 'Sweet, woody fruit'),
-- HEART NOTES - Spicy
('Cardamom', 'heart', 'spicy', 7, 6, '["adventurous","bold","sophisticated"]', '["evening","date","special"]', '["cool","temperate"]', '["25-34","35-44","45+"]', 'Warm, aromatic spice'),
('Cinnamon', 'heart', 'spicy', 8, 6, '["bold","sensual","adventurous"]', '["evening","winter","special"]', '["cool","cold"]', '["25-34","35-44"]', 'Sweet, warm spice'),
('Clove', 'heart', 'spicy', 8, 7, '["bold","adventurous","sophisticated"]', '["evening","special","winter"]', '["cool","cold"]', '["35-44","45+"]', 'Rich, warm aromatic'),
('Black Pepper', 'heart', 'spicy', 7, 5, '["bold","energetic","adventurous"]', '["sport","evening","outdoor"]', '["cool","temperate"]', '["25-34","35-44"]', 'Sharp, peppery warmth'),
('Ginger', 'heart', 'spicy', 7, 5, '["energetic","adventurous","bold"]', '["sport","daily","outdoor"]', '["cool","temperate","warm"]', '["18-24","25-34","35-44"]', 'Zesty, warm spice'),
('Saffron', 'heart', 'spicy', 8, 7, '["sophisticated","bold","elegant"]', '["evening","special","date"]', '["cool","temperate"]', '["35-44","45+"]', 'Luxurious, golden spice'),
-- BASE NOTES - Woody
('Sandalwood', 'base', 'woody', 6, 9, '["calm","sophisticated","sensual"]', '["meditation","evening","date"]', '["warm","temperate","tropical"]', '["25-34","35-44","45+"]', 'Creamy, warm wood'),
('Cedarwood', 'base', 'woody', 5, 8, '["calm","sophisticated","bold"]', '["daily","work","outdoor"]', '["temperate","cool"]', '["25-34","35-44","45+"]', 'Dry, pencil-shaving wood'),
('Oud', 'base', 'woody', 9, 10, '["bold","sophisticated","sensual"]', '["evening","special","luxury"]', '["cool","cold","temperate"]', '["35-44","45+"]', 'Rich, complex precious wood'),
('Patchouli', 'base', 'woody', 7, 9, '["bold","creative","adventurous"]', '["evening","casual","outdoor"]', '["warm","tropical","temperate"]', '["25-34","35-44"]', 'Earthy, sweet, musky wood'),
('Vetiver', 'base', 'woody', 6, 8, '["calm","sophisticated","bold"]', '["work","daily","evening"]', '["warm","temperate"]', '["25-34","35-44","45+"]', 'Smoky, earthy root'),
('Guaiac Wood', 'base', 'woody', 5, 8, '["calm","sophisticated","creative"]', '["work","evening","daily"]', '["cool","temperate"]', '["35-44","45+"]', 'Smoky, slightly sweet wood'),
('Cypress', 'base', 'woody', 5, 7, '["calm","adventurous","sophisticated"]', '["outdoor","daily","sport"]', '["temperate","cool"]', '["25-34","35-44"]', 'Green, coniferous wood'),
-- BASE NOTES - Oriental
('Amber', 'base', 'oriental', 7, 9, '["sensual","sophisticated","romantic"]', '["evening","date","special"]', '["cool","cold","temperate"]', '["25-34","35-44","45+"]', 'Warm, resinous golden sweetness'),
('Vanilla', 'base', 'oriental', 6, 8, '["romantic","gentle","playful"]', '["date","evening","casual"]', '["cool","cold","temperate"]', '["18-24","25-34","35-44"]', 'Sweet, comforting warmth'),
('Musk', 'base', 'oriental', 5, 9, '["sensual","sophisticated","calm"]', '["date","evening","daily"]', '["warm","temperate","cool"]', '["25-34","35-44","45+"]', 'Clean, skin-like animalistic note'),
('Incense', 'base', 'oriental', 8, 9, '["spiritual","sophisticated","bold"]', '["meditation","evening","special"]', '["cool","cold"]', '["35-44","45+"]', 'Smoky, sacred resin'),
('Myrrh', 'base', 'oriental', 7, 8, '["spiritual","sophisticated","calm"]', '["meditation","evening","special"]', '["cool","cold","temperate"]', '["35-44","45+"]', 'Warm, balsamic resin'),
('Benzoin', 'base', 'oriental', 6, 8, '["gentle","romantic","calm"]', '["evening","date","meditation"]', '["cool","cold"]', '["25-34","35-44","45+"]', 'Sweet, vanilla-like resin'),
-- BASE NOTES - Gourmand
('Caramel', 'base', 'gourmand', 6, 7, '["playful","romantic","gentle"]', '["casual","date","evening"]', '["cool","cold"]', '["18-24","25-34"]', 'Sweet, buttery richness'),
('Coffee', 'base', 'gourmand', 8, 7, '["bold","energetic","creative"]', '["daily","work","casual"]', '["cool","cold","temperate"]', '["25-34","35-44"]', 'Roasted, bitter-sweet depth'),
('Chocolate', 'base', 'gourmand', 7, 7, '["romantic","sensual","playful"]', '["date","evening","casual"]', '["cool","cold"]', '["18-24","25-34","35-44"]', 'Rich, dark cocoa'),
('Honey', 'base', 'gourmand', 5, 7, '["gentle","romantic","calm"]', '["date","casual","daily"]', '["warm","temperate"]', '["25-34","35-44"]', 'Sweet, golden nectar'),
('Almond', 'base', 'gourmand', 5, 6, '["gentle","creative","calm"]', '["daily","casual","work"]', '["temperate","cool"]', '["25-34","35-44"]', 'Nutty, marzipan sweetness'),
('Coconut', 'base', 'gourmand', 5, 6, '["playful","adventurous","romantic"]', '["casual","outdoor","beach"]', '["tropical","warm","hot"]', '["18-24","25-34"]', 'Tropical, creamy sweetness'),
('Tonka Bean', 'base', 'gourmand', 6, 8, '["sophisticated","romantic","gentle"]', '["evening","date","special"]', '["cool","cold","temperate"]', '["25-34","35-44","45+"]', 'Warm, almond-vanilla complexity');
